CREATE ALIAS IF NOT EXISTS READ_BLOB FOR "org.h2.tools.Recover.readBlob";
CREATE ALIAS IF NOT EXISTS READ_CLOB FOR "org.h2.tools.Recover.readClob";
CREATE ALIAS IF NOT EXISTS READ_BLOB_DB FOR "org.h2.tools.Recover.readBlobDb";
CREATE ALIAS IF NOT EXISTS READ_CLOB_DB FOR "org.h2.tools.Recover.readClobDb";
-- pageSize: 2048 writeVersion: 3 readVersion: 3
-- head 1: writeCounter: 60 log 4:5/16 crc -542765715 (ok)
-- head 2: writeCounter: 60 log 4:5/16 crc -542765715 (ok)
-- log 4:5/16
-- page 3: free list 
-- 3 1101111 1111111
-- page 4: data leaf (last) parent: 0 table: -1 entries: 13 columns: 6
CREATE TABLE O_M1(C0 VARCHAR, C1 VARCHAR, C2 VARCHAR, C3 VARCHAR, C4 VARCHAR, C5 VARCHAR);
INSERT INTO O_M1 VALUES(0, 0, 0, 12, 'OFF,0,,', '0,1,2,3');
INSERT INTO O_M1 VALUES(2, 0, 2, 11, 'OFF,0,,', '0,1,2');
INSERT INTO O_M1 VALUES(3, 1, 2, 0, 'OFF,0,,d', '0');
INSERT INTO O_M1 VALUES(5, 1, 2, 10, 'OFF,0,,', '2');
INSERT INTO O_M1 VALUES(6, 0, 6, 9, 'OFF,0,,', '0,1,2,3,4');
INSERT INTO O_M1 VALUES(7, 1, 6, 8, 'OFF,0,,', '0,1');
INSERT INTO O_M1 VALUES(9, 1, 6, 7, 'OFF,0,,', '4,0');
INSERT INTO O_M1 VALUES(10, 0, 10, 6, 'OFF,0,,', '0,1,2');
INSERT INTO O_M1 VALUES(11, 1, 10, 0, 'OFF,0,,d', '0');
INSERT INTO O_M1 VALUES(14, 0, 14, 16, 'OFF,0,,', '0,1');
INSERT INTO O_M1 VALUES(15, 1, 14, 0, 'OFF,0,,d', '0');
INSERT INTO O_M1 VALUES(17, 0, 17, 15, 'OFF,0,,', '0,1,2');
INSERT INTO O_M1 VALUES(18, 1, 17, 0, 'OFF,0,,d', '0');
-- page 6: data leaf (last) parent: 0 table: 10 entries: 0 columns: 3
-- page 7: b-tree leaf (last) parent: 0 index: 9 entries: 0
-- page 8: b-tree leaf (last) parent: 0 index: 7 entries: 0
-- page 9: data leaf (last) parent: 0 table: 6 entries: 0 columns: 5
-- page 10: b-tree leaf (last) parent: 0 index: 5 entries: 0
-- page 11: data leaf (last) parent: 0 table: 2 entries: 0 columns: 3
-- page 12: data node parent: 0 table: 0 entries: 1 rowCount: 19
-- page 13: data leaf (last) parent: 12 table: 0 entries: 10 columns: 4
CREATE TABLE O_0(C0 VARCHAR, C1 VARCHAR, C2 VARCHAR, C3 VARCHAR);
INSERT INTO O_0 VALUES(1, 0, 6, 'SET CREATE_BUILD 170');
INSERT INTO O_0 VALUES(2, 0, 0, STRINGDECODE('CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOBS(\n    ID BIGINT NOT NULL,\n    BYTE_COUNT BIGINT,\n    TABLE INT\n)\nHIDDEN'));
INSERT INTO O_0 VALUES(3, 0, 1, 'CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_2 ON INFORMATION_SCHEMA.LOBS(ID)');
INSERT INTO O_0 VALUES(4, 0, 5, 'ALTER TABLE INFORMATION_SCHEMA.LOBS ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_2 PRIMARY KEY(ID) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_2');
INSERT INTO O_0 VALUES(5, 0, 1, 'CREATE INDEX IF NOT EXISTS INFORMATION_SCHEMA.INDEX_LOB_TABLE ON INFORMATION_SCHEMA.LOBS(TABLE)');
INSERT INTO O_0 VALUES(6, 0, 0, STRINGDECODE('CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOB_MAP(\n    LOB BIGINT NOT NULL,\n    SEQ INT NOT NULL,\n    POS BIGINT,\n    HASH INT,\n    BLOCK BIGINT\n)\nHIDDEN'));
INSERT INTO O_0 VALUES(7, 0, 1, 'CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_3 ON INFORMATION_SCHEMA.LOB_MAP(LOB, SEQ)');
INSERT INTO O_0 VALUES(8, 0, 5, 'ALTER TABLE INFORMATION_SCHEMA.LOB_MAP ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_3 PRIMARY KEY(LOB, SEQ) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_3');
INSERT INTO O_0 VALUES(9, 0, 1, 'CREATE INDEX IF NOT EXISTS INFORMATION_SCHEMA.INDEX_LOB_MAP_DATA_LOB ON INFORMATION_SCHEMA.LOB_MAP(BLOCK, LOB)');
INSERT INTO O_0 VALUES(10, 0, 0, STRINGDECODE('CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOB_DATA(\n    BLOCK BIGINT NOT NULL,\n    COMPRESSED INT,\n    DATA BINARY\n)\nHIDDEN'));
-- page 14: data leaf (last) parent: 12 table: 0 entries: 9 columns: 4
INSERT INTO O_0 VALUES(11, 0, 1, 'CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_9 ON INFORMATION_SCHEMA.LOB_DATA(BLOCK)');
INSERT INTO O_0 VALUES(12, 0, 5, 'ALTER TABLE INFORMATION_SCHEMA.LOB_DATA ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_9 PRIMARY KEY(BLOCK) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_9');
INSERT INTO O_0 VALUES(13, 0, 2, 'CREATE USER IF NOT EXISTS JOHNNY SALT ''8a64fa4cf01f0452'' HASH ''8247babd9a800b942fc8b0383425895b02651aab3aa48737b5bde1f24729cba6'' ADMIN');
INSERT INTO O_0 VALUES(14, 0, 0, STRINGDECODE('CREATE CACHED TABLE PUBLIC.KLANT(\n    ID INT NOT NULL,\n    NAME VARCHAR(255)\n)'));
INSERT INTO O_0 VALUES(15, 0, 1, 'CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_4 ON PUBLIC.KLANT(ID)');
INSERT INTO O_0 VALUES(16, 0, 5, 'ALTER TABLE PUBLIC.KLANT ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID) INDEX PUBLIC.PRIMARY_KEY_4');
INSERT INTO O_0 VALUES(17, 0, 0, STRINGDECODE('CREATE CACHED TABLE PUBLIC.PROJECT(\n    ID INT NOT NULL,\n    KLANTID INT,\n    NAME VARCHAR(255)\n)'));
INSERT INTO O_0 VALUES(18, 0, 1, 'CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_1 ON PUBLIC.PROJECT(ID)');
INSERT INTO O_0 VALUES(19, 0, 5, 'ALTER TABLE PUBLIC.PROJECT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID) INDEX PUBLIC.PRIMARY_KEY_1');
-- page 15: log data
-- page 16: log data
---- Schema ----
SET CREATE_BUILD 170;
CREATE USER IF NOT EXISTS JOHNNY SALT '8a64fa4cf01f0452' HASH '8247babd9a800b942fc8b0383425895b02651aab3aa48737b5bde1f24729cba6' ADMIN;
CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOBS(
    ID BIGINT NOT NULL,
    BYTE_COUNT BIGINT,
    TABLE INT
)
HIDDEN;
CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOB_MAP(
    LOB BIGINT NOT NULL,
    SEQ INT NOT NULL,
    POS BIGINT,
    HASH INT,
    BLOCK BIGINT
)
HIDDEN;
CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOB_DATA(
    BLOCK BIGINT NOT NULL,
    COMPRESSED INT,
    DATA BINARY
)
HIDDEN;
CREATE CACHED TABLE PUBLIC.KLANT(
    ID INT NOT NULL,
    NAME VARCHAR(255)
);
CREATE CACHED TABLE PUBLIC.PROJECT(
    ID INT NOT NULL,
    KLANTID INT,
    NAME VARCHAR(255)
);
DROP TABLE O_0;
DROP TABLE O_M1;
DROP ALIAS READ_BLOB;
DROP ALIAS READ_CLOB;
DROP ALIAS READ_BLOB_DB;
DROP ALIAS READ_CLOB_DB;
CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_2 ON INFORMATION_SCHEMA.LOBS(ID);
CREATE INDEX IF NOT EXISTS INFORMATION_SCHEMA.INDEX_LOB_TABLE ON INFORMATION_SCHEMA.LOBS(TABLE);
CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_3 ON INFORMATION_SCHEMA.LOB_MAP(LOB, SEQ);
CREATE INDEX IF NOT EXISTS INFORMATION_SCHEMA.INDEX_LOB_MAP_DATA_LOB ON INFORMATION_SCHEMA.LOB_MAP(BLOCK, LOB);
CREATE PRIMARY KEY IF NOT EXISTS INFORMATION_SCHEMA.PRIMARY_KEY_9 ON INFORMATION_SCHEMA.LOB_DATA(BLOCK);
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_4 ON PUBLIC.KLANT(ID);
CREATE PRIMARY KEY PUBLIC.PRIMARY_KEY_1 ON PUBLIC.PROJECT(ID);
ALTER TABLE INFORMATION_SCHEMA.LOBS ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_2 PRIMARY KEY(ID) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_2;
ALTER TABLE INFORMATION_SCHEMA.LOB_MAP ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_3 PRIMARY KEY(LOB, SEQ) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_3;
ALTER TABLE INFORMATION_SCHEMA.LOB_DATA ADD CONSTRAINT IF NOT EXISTS INFORMATION_SCHEMA.CONSTRAINT_9 PRIMARY KEY(BLOCK) INDEX INFORMATION_SCHEMA.PRIMARY_KEY_9;
ALTER TABLE PUBLIC.KLANT ADD CONSTRAINT PUBLIC.CONSTRAINT_4 PRIMARY KEY(ID) INDEX PUBLIC.PRIMARY_KEY_4;
ALTER TABLE PUBLIC.PROJECT ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY(ID) INDEX PUBLIC.PRIMARY_KEY_1;
---- Transaction log ----
-- ERROR: checksum mismatch page: 5
---- Statistics ----
-- page count: 17, free: 1
-- page data bytes: head 166, empty 9735, rows 2387 (21% full)
-- free 5%, 1 page(s)
-- data leaf 35%, 6 page(s)
-- data node 5%, 1 page(s)
-- btree leaf 17%, 3 page(s)
-- free list 5%, 1 page(s)
-- stream data 11%, 2 page(s)
