/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trekbankDialogs;

import TrekbankExceptions.NoCustomerSelectedException;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import trekbankDatabaseObjects.Customer;
import trekbankDatabaseObjects.Database;
import trekbankDatabaseObjects.Project;

/**
 *
 * @author Johnny
 */
public class addNewProjectDialog extends java.awt.Dialog {

    private static String newProjectName = null;
    private static Customer chosenCustomer = null;
    /**
     * Creates new form addNewCustomerDialog
     */
    public addNewProjectDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(new Point((screenSize.width - 300)/2, (screenSize.height - 200)/2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        projectNameField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        searchCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(214, 217, 223));
        setResizable(false);
        setTitle("Klant toevoegen");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("Typ hier de naam voor een nieuw project");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        projectNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameFieldActionPerformed(evt);
            }
        });
        projectNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                projectNameFieldKeyReleased(evt);
            }
        });

        addButton.setText("Voeg toe");
        addButton.setToolTipText("Als u op deze knop klikt wordt de klant toegevoegd aan de database");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Annuleer");
        cancelButton.setToolTipText("Als u deze knop gebruikt wordt er geen klant geselecteerd en keert u terug naar waar u vandaan kwam");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecteer hier een klant om aan dit project te koppelen");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        searchCustomer.setText("Zoek klant om te koppelen");
        searchCustomer.setToolTipText("Dit opent een zoek venster waar u 1 klant kunt selecteren");
        searchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectNameField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(addButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void projectNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectNameFieldKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_projectNameFieldKeyReleased

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if (projectNameField.getText().isEmpty() || projectNameField.getText() == null){
            newProjectName = null;
            JOptionPane.showMessageDialog(null, "Er is geen naam ingevuld voor het nieuwe project\nVoer een naam in of annuleer", "Project toevoegen mislukt", JOptionPane.WARNING_MESSAGE);
        } else if (chosenCustomer == null){
            JOptionPane.showMessageDialog(null, "Er is geen klant gekoppeld aan dit project\nSelecteer een klant of annuleer", "Project toevoegen mislukt", JOptionPane.WARNING_MESSAGE);
        } else {
            newProjectName = projectNameField.getText();
            closeDialog(null);
        }   
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        newProjectName = null;
        closeDialog(null);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void projectNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectNameFieldActionPerformed

    private void searchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerActionPerformed
        // TODO add your handling code here:
        try {
            chosenCustomer = Dialogs.showSearchCustomerDialog(null, false).get(0);
        } catch (NoCustomerSelectedException e){
            chosenCustomer = null;
        }
    }//GEN-LAST:event_searchCustomerActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField projectNameField;
    private javax.swing.JButton searchCustomer;
    // End of variables declaration//GEN-END:variables

    public static boolean showDialog(java.awt.Frame parent){
        addNewProjectDialog dialog = new addNewProjectDialog(parent, true);
        dialog.setVisible(true);
        return (chosenCustomer != null && !newProjectName.isEmpty() && Database.insertNewProjectWithUniqueId(new Project(0, chosenCustomer.getId(), newProjectName)) != -1);
    }
    
}
