/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trekbankDialogs;

import TrekbankExceptions.NoLoggedInUserException;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import trekbank.MainScreen;
import trekbankDatabaseObjects.Database;
import trekbankDatabaseObjects.User;

/**
 *
 * @author Johnny
 */
public class loginDialog extends java.awt.Dialog {

    private static User loggedInUser = null;
    /**
     * Creates new form loginDialog
     */
    public loginDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents(); 
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(new Point((screenSize.width - 600)/2, (screenSize.height - 300)/2));
        loadUsers();
        setMinimumSize(getSize());
    }
    
    private void loadUsers(){
        lisOfUsers.removeAll();
        for (User user : Database.getAllUsers()){
            lisOfUsers.add(user.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUserField = new javax.swing.JTextField();
        newUserPassword = new javax.swing.JPasswordField();
        newUserPassword2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        logInButton = new javax.swing.JButton();
        loginPassword = new javax.swing.JPasswordField();
        addNewUser = new javax.swing.JButton();
        lisOfUsers = new java.awt.List();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(214, 217, 223));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        newUserField.setToolTipText("Hier vult u de naam van de nieuwe gebruiker in");
        newUserField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newUserFieldKeyPressed(evt);
            }
        });

        newUserPassword.setText("jPasswordField2");
        newUserPassword.setToolTipText("Hier vult u het wachtwoord van de nieuwe gebruiker in");
        newUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newUserPasswordKeyPressed(evt);
            }
        });

        newUserPassword2.setText("jPasswordField3");
        newUserPassword2.setToolTipText("Hier vult u ter bevestiging nog een keer het wachtwoord in van de nieuwe gebruiker in");
        newUserPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newUserPassword2KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Of maak hier een nieuwe gebruiker aan");
        jLabel2.setToolTipText("Voer eerst de nieuwe naam in. En dan twee keer het gewenste wachtwoord.");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        logInButton.setText("Log in");
        logInButton.setToolTipText("Hier logt u in");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        loginPassword.setToolTipText("Hier vult u uw wachtwoord in");
        loginPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPasswordActionPerformed(evt);
            }
        });
        loginPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginPasswordKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginPasswordKeyReleased(evt);
            }
        });

        addNewUser.setText("Maak nieuwe gebruiker aan");
        addNewUser.setToolTipText("Hier mee maakt u de nieuwe gebruiker aan");
        addNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserActionPerformed(evt);
            }
        });

        lisOfUsers.setBackground(java.awt.Color.white);
        lisOfUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lisOfUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lisOfUsersMouseClicked(evt);
            }
        });
        lisOfUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisOfUsersActionPerformed(evt);
            }
        });
        lisOfUsers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lisOfUsersKeyPressed(evt);
            }
        });

        jLabel3.setText("Voer hier de naam van de nieuwe gebruiker in");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Log hier in");
        jLabel1.setToolTipText("Selecteer eerst een gebruiker in de lijst hieronder. En voer dan uw wachtwoord in.");

        jLabel5.setText("Voer nogmaals het nieuwe wachtwoord in");

        jLabel4.setText("Voer hier het wachtwoord in van de nieuwe gebruiker");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lisOfUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newUserField)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newUserPassword)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(newUserPassword2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newUserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newUserPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(addNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lisOfUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        loggedInUser = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        if (lisOfUsers.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "U heeft geen gebruiker geselecteerd", "Geen gebruiker", JOptionPane.WARNING_MESSAGE);
            return;
        }
        for (User user : Database.getAllUsers()){
            String selectedUser = lisOfUsers.getSelectedItem();
            String password = loginPassword.getText();
            if (selectedUser.equals(user.getName()) && password.equals(user.getPassword())){
                loggedInUser = user;
                setVisible(false);
                dispose();
                return;
            }
        }
        JOptionPane.showMessageDialog(null, "U heeft een fout wachtwoord ingevuld", "Fout wachtwoord", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_logInButtonActionPerformed

    private void addNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserActionPerformed
        if (newUserField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "U heeft geen naam ingevuld\nVoer een naam in", "Geen geldige naam", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        for (User user : Database.getAllUsers()){
            if (newUserField.getText().equals(user.getName())){
                JOptionPane.showMessageDialog(null, "U heeft een naam ingevuld die al gebruikt wordt\nVoer een andere naam in", "Gebruiker bestaat al", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        if (newUserPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "U heeft geen wachtwoord ingevuld\nVoer een wachtwoord in", "Wachtwoord fout", JOptionPane.WARNING_MESSAGE);
            newUserPassword.setText("");
            newUserPassword2.setText("");
            return;
        }
        if (!newUserPassword.getText().equals(newUserPassword2.getText())){
            JOptionPane.showMessageDialog(null, "De wachtwoorden komen niet overeen\nVoer het wachtwoord opnieuw in", "Wachtwoord fout", JOptionPane.WARNING_MESSAGE);
            newUserPassword.setText("");
            newUserPassword2.setText("");
            return;
        }
        
        Database.insertNewUserWithUniqueId(new User(0, newUserField.getText(), newUserPassword.getText()));
        loadUsers();
    }//GEN-LAST:event_addNewUserActionPerformed

    private void lisOfUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisOfUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lisOfUsersActionPerformed

    private void lisOfUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lisOfUsersMouseClicked
        if (evt.getClickCount() == 2) {
            loginPassword.requestFocus();
        }
    }//GEN-LAST:event_lisOfUsersMouseClicked

    private void loginPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPasswordKeyReleased
        
    }//GEN-LAST:event_loginPasswordKeyReleased

    private void loginPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPasswordActionPerformed

    private void loginPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logInButtonActionPerformed(null);
        }
    }//GEN-LAST:event_loginPasswordKeyPressed

    private void newUserFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newUserFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            newUserPassword.requestFocus();
        }
    }//GEN-LAST:event_newUserFieldKeyPressed

    private void newUserPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newUserPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            newUserPassword2.requestFocus();
        }
    }//GEN-LAST:event_newUserPasswordKeyPressed

    private void newUserPassword2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newUserPassword2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addNewUserActionPerformed(null);
        }
    }//GEN-LAST:event_newUserPassword2KeyPressed

    private void lisOfUsersKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lisOfUsersKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            loginPassword.requestFocus();
        }
    }//GEN-LAST:event_lisOfUsersKeyPressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.List lisOfUsers;
    private javax.swing.JButton logInButton;
    private javax.swing.JPasswordField loginPassword;
    private javax.swing.JTextField newUserField;
    private javax.swing.JPasswordField newUserPassword;
    private javax.swing.JPasswordField newUserPassword2;
    // End of variables declaration//GEN-END:variables
    
    
    public static User showScreen(java.awt.Frame parent) throws NoLoggedInUserException{
        loginDialog dialog = new loginDialog(parent, true);
        dialog.setVisible(true);
        if (loggedInUser != null){
            return loggedInUser;
        } else {
            throw new NoLoggedInUserException();
        }
    }


}

