/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package trekbankDialogs;

import TrekbankExceptions.NoMeasureProfileDefined;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import trekbank.MainScreen;
import trekbank.MeasureSubProfile;

/**
 *
 * @author Johnny
 */
public class newMeasureProfileDialog extends java.awt.Dialog {

    private int numberOfMeasuresToDo;
    private int currentMeasurement;
    private ArrayList<MeasureSubProfile> measurements;
    private static ArrayList<MeasureSubProfile> finalMeasurements;
    /**
     * Creates new form newMeasureProfileDialog
     */
    public newMeasureProfileDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        setSize(new Dimension(350, 400));
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(new Point((screenSize.width - 350)/2, (screenSize.height - 400)/2));
        
        setBackground(new Color(214,217,223));

        
        numberOfMeasures.setModel(new SpinnerNumberModel(1, 1, 15, 1));
        numberOfSubMeasures.setModel(new SpinnerNumberModel(1, 1, 50, 1));
        
        currentMeasurement = 1;
        
        cancelLockNumberOfMeasures.setEnabled(false);
        numberOfSubMeasures.setEnabled(false);
        discription.setEnabled(false);
        lockNumberOfSubMeasures.setEnabled(false);
        finished.setEnabled(false);
        next.setEnabled(false);
        cancelLockNumberOfSubMeasures.setEnabled(false);
        
        numberOfSubMeasuresStateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numberOfMeasures = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        numberOfSubMeasures = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        discription = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        lockNumberOfMeasures = new javax.swing.JButton();
        lockNumberOfSubMeasures = new javax.swing.JButton();
        finished = new javax.swing.JButton();
        cancelLockNumberOfMeasures = new javax.swing.JButton();
        cancelLockNumberOfSubMeasures = new javax.swing.JButton();

        setBackground(new java.awt.Color(214, 217, 223));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setText("De hoeveelheid metingen die gedaan worden: ");

        numberOfMeasures.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberOfMeasuresStateChanged(evt);
            }
        });

        jLabel2.setText("De 1e meting, meet");

        numberOfSubMeasures.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberOfSubMeasuresStateChanged(evt);
            }
        });

        jLabel3.setText("voorwerpen");

        jLabel4.setText("Geef een beschrijving voor deze voorwerpen");

        next.setText("Volgende >");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        lockNumberOfMeasures.setText("OK");
        lockNumberOfMeasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockNumberOfMeasuresActionPerformed(evt);
            }
        });

        lockNumberOfSubMeasures.setText("OK");
        lockNumberOfSubMeasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockNumberOfSubMeasuresActionPerformed(evt);
            }
        });

        finished.setText("Klaar");
        finished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishedActionPerformed(evt);
            }
        });

        cancelLockNumberOfMeasures.setText("Annuleer");
        cancelLockNumberOfMeasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLockNumberOfMeasuresActionPerformed(evt);
            }
        });

        cancelLockNumberOfSubMeasures.setText("Annuleer");
        cancelLockNumberOfSubMeasures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLockNumberOfSubMeasuresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finished, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberOfMeasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lockNumberOfMeasures, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelLockNumberOfMeasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(discription)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numberOfSubMeasures, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lockNumberOfSubMeasures, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelLockNumberOfSubMeasures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numberOfMeasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lockNumberOfMeasures)
                            .addComponent(cancelLockNumberOfMeasures))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(numberOfSubMeasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lockNumberOfSubMeasures)
                    .addComponent(cancelLockNumberOfSubMeasures))
                .addGap(47, 47, 47)
                .addComponent(next)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finished, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        finalMeasurements = null;
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void numberOfSubMeasuresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberOfSubMeasuresStateChanged
        if ((Integer) numberOfSubMeasures.getValue() > 1){
            jLabel3.setText("voorwerpen");
            jLabel4.setText("Geef een beschrijving voor deze voorwerpen:");
        } else {
            jLabel3.setText("voorwerp");
            jLabel4.setText("Geef een beschrijving voor dit voorwerp:");
        }
    }//GEN-LAST:event_numberOfSubMeasuresStateChanged

    private void numberOfMeasuresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberOfMeasuresStateChanged
        //jLabel2.setText("De " + (int) numberOfMeasures.getValue() + "e meting, meet");
        
        
    }//GEN-LAST:event_numberOfMeasuresStateChanged

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        currentMeasurement++;
        jLabel2.setText("De " + currentMeasurement + "e meting, meet");
        numberOfSubMeasures.setEnabled(true);
        discription.setEnabled(true);
        next.setEnabled(false);

        
        measurements.add(new MeasureSubProfile((Integer) numberOfSubMeasures.getValue(), discription.getText()));   
        discription.setText("");
        numberOfSubMeasures.setValue(1);
        cancelLockNumberOfSubMeasures.setEnabled(false);
        lockNumberOfSubMeasures.setEnabled(true);
    }//GEN-LAST:event_nextActionPerformed

    private void lockNumberOfMeasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockNumberOfMeasuresActionPerformed
        numberOfMeasures.setEnabled(false);
        cancelLockNumberOfMeasures.setEnabled(true);
        numberOfMeasuresToDo = (Integer) numberOfMeasures.getValue();
        //next.setEnabled((int) numberOfMeasures.getValue() == 1);
        lockNumberOfMeasures.setEnabled(false);
        measurements = new ArrayList<MeasureSubProfile>();
        
        numberOfSubMeasures.setEnabled(true);
        discription.setEnabled(true);
        lockNumberOfSubMeasures.setEnabled(true);
        
    }//GEN-LAST:event_lockNumberOfMeasuresActionPerformed

    private void showNoEmptyDiscriptionMessage(){
        JOptionPane.showMessageDialog(null, "De beschrijving mag niet leeg zijn", "Lege beschrijving", JOptionPane.WARNING_MESSAGE);
    }
    private void lockNumberOfSubMeasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockNumberOfSubMeasuresActionPerformed
        
//        if (discription.getText().isEmpty()){
//            showNoEmptyDiscriptionMessage();
//            return;
//        }
        lockNumberOfSubMeasures.setEnabled(false);
        cancelLockNumberOfSubMeasures.setEnabled(true);
        numberOfSubMeasures.setEnabled(false);
        discription.setEnabled(false);
        if (currentMeasurement == numberOfMeasuresToDo) finished.setEnabled(true);
        next.setEnabled((Integer) numberOfMeasures.getValue() != 1 && currentMeasurement != numberOfMeasuresToDo);
    }//GEN-LAST:event_lockNumberOfSubMeasuresActionPerformed

    private void finishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishedActionPerformed
//        if (discription.getText().isEmpty()){
//            showNoEmptyDiscriptionMessage();
//            return;
//        }
        measurements.add(new MeasureSubProfile((Integer) numberOfSubMeasures.getValue(), discription.getText()));  
//        for (MeasureSubProfile m : measurements){
//            System.out.println(m.toString());
//        }
        
        finalMeasurements = new ArrayList<MeasureSubProfile>(measurements);
        dispose();
    }//GEN-LAST:event_finishedActionPerformed

    private void cancelLockNumberOfMeasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLockNumberOfMeasuresActionPerformed
        cancelLockNumberOfMeasures.setEnabled(false);
        cancelLockNumberOfSubMeasures.setEnabled(false);
        lockNumberOfMeasures.setEnabled(true);
        numberOfMeasures.setEnabled(true);
        finished.setEnabled(false);
        numberOfMeasures.setValue(1);
        lockNumberOfSubMeasures.setEnabled(false);
        discription.setText("");
        discription.setEnabled(false);
        lockNumberOfSubMeasures.setEnabled(false);
        numberOfSubMeasures.setValue(1);
        numberOfSubMeasures.setEnabled(false);
        currentMeasurement = 1;
        jLabel2.setText("De " + currentMeasurement + "e meting, meet");
    }//GEN-LAST:event_cancelLockNumberOfMeasuresActionPerformed

    private void cancelLockNumberOfSubMeasuresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLockNumberOfSubMeasuresActionPerformed
        cancelLockNumberOfSubMeasures.setEnabled(false);
        discription.setEnabled(true);
        lockNumberOfSubMeasures.setEnabled(true);
        next.setEnabled(false);
        finished.setEnabled(false);
        numberOfSubMeasures.setEnabled(true);
    }//GEN-LAST:event_cancelLockNumberOfSubMeasuresActionPerformed

    /**
     * 
     */
    public static ArrayList<MeasureSubProfile> showDialog(java.awt.Frame parent) throws NoMeasureProfileDefined {
        newMeasureProfileDialog dialog = new newMeasureProfileDialog(parent, true);
        dialog.setVisible(true);
        
        if (finalMeasurements == null || finalMeasurements.isEmpty()){
            throw new NoMeasureProfileDefined();
        } else {
            return finalMeasurements;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelLockNumberOfMeasures;
    private javax.swing.JButton cancelLockNumberOfSubMeasures;
    private javax.swing.JTextField discription;
    private javax.swing.JButton finished;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton lockNumberOfMeasures;
    private javax.swing.JButton lockNumberOfSubMeasures;
    private javax.swing.JButton next;
    private javax.swing.JSpinner numberOfMeasures;
    private javax.swing.JSpinner numberOfSubMeasures;
    // End of variables declaration//GEN-END:variables
}
